### ISSUE TITLE
Lags when playing long time

### ISSUE THREAD

**Issue by Vineg** [RealDebugMonkey/ZeachCobbler#1]
After playing for ~15 min, game starts to lag every second.

**Comment by RealDebugMonkey** [comment]
and you don't experience the same issue when playing vanilla?

**Comment by RealDebugMonkey** [comment]
In order to allow for non-technical users to better isolate the source of slowdown issues I will be moving to make each feature have an on/off toggle checkbox that will bypass all calculations. 

As for this issue, as you get bigger you can see more of the board. This generally shouldn't impact anything. However, the grazer uses an O(n^2) algorithm, so as more points and food pellets are visible, more calculations take place. I advise not using grazer at large sizes. Also try pressing 'C' to disable all visual assists and see if that makes a difference. Feel free to come back if you are better able to isolate the issue or otherwise provide more information.
