### ISSUE TITLE
'E' doesn't work properly

### ISSUE THREAD

**Issue by toto2379** [RealDebugMonkey/ZeachCobbler#15]
A "recent" update limited how fast you could eject mass : 
https://www.reddit.com/r/Agario/comments/3cbtua/ejected_mass_scales_now_experimental/csubxyi

> The limit used to be 10 ejects per second, now it's 7

Now when I press 'E' on an unfed virus, I only feed it 5 times instead of 7.

On an unrelated note, I think the reason why this mod is seen as primarily a bot rather than a 'Hack mod' is because none of the mods of the "Hack" section contain any botting, while yours have botting.

**Comment by RealDebugMonkey** [comment]
In the script you will find a variable on line 1266 named "msDelayBetweenShots" and is currently set to 75ms.
If you prefer not to wait for me to have time to find an optimal value and If you feel comfortable doing so you can move that value to a larger value to account for the changes you describe. If you find a value that works better I will update the code with the new and improved value.

Otherwise, I'll try and fix it this weekend after I figure out the impact of the facebook changes.

**Comment by RealDebugMonkey** [comment]
Added new editable value to version 0.27.2 which allows you to set the delay between shots.
upped the default value from 70ms to 100ms. 7 shots per second is 145ish, but that seems way too long. i'd rather just tap the button twice if i need to.

You should be able to tweak this to your liking. let me know if you encounter any issues
