### ISSUE TITLE
Splitting

### ISSUE THREAD

**Issue by KickingRG** [RealDebugMonkey/ZeachCobbler#31]
When grazer is enabled and when you split both blobs go separate ways and die.

**Comment by Szigerd** [comment]
Can confirm this. Grazer is unusable when split. Must have to do with new Click to lock feature which is useless anyway imho. The grazer did it itself in the past when necessary.
Please revert to old code! Grazer is now useless when split, and that is where it was most valuable in the past to get you out of tricky situations.
Thx, Szigerd

**Comment by Szigerd** [comment]
Ah, with switch multiblob disabled, Grazer shows old behaviour (but does not show visualisation on 2nd  blob as before.
tldr: grazer + multiblob = FAIL

**Comment by RealDebugMonkey** [comment]
:( Sorry about that.
I'll make multiblob split off by default, fix the visualization, and try to make multiblob work better

**Comment by KickingRG** [comment]
Do you have a way I could contact you personally? Steam,Skype,ect? @RealDebugMonkey

**Comment by RealDebugMonkey** [comment]
@KickingRG The [best place to contact me is in IRC](https://kiwiirc.com/client/irc.rizon.net/?nick=CobblerUser|?#agariomods) in the #agariomods channel on [rizon](http://www.rizon.net/)

**Comment by RealDebugMonkey** [comment]
@KickingRG I've changed to code so multi-blob grazer is off by default -- people will have to go in and manually enable it now.
@Szigerd -- Since grazing visualization and calculations are dependent on the currently-selected cell it doesn't make sense to draw grazer visualizations for any other cell. There's actually a related bug right now where if you switch active cells while grazing it will continue showing threat lines for the old cell.
