### ISSUE TITLE
Can You Help Me Out?

### ISSUE THREAD

**Issue by JoJoFool** [RealDebugMonkey/ZeachCobbler#73]
Hi I have been using your code i read that you don't have time to devote to this anymore however I really liked one feature the most which was the virus popper could you give me stand alone just virus popper? I would be willing to pay for it. I don't need the bot. 

Thanks Friend

**Comment by ghost** [comment]
I don't understand. Standalone virus popper? Why not use the Zeach Cobbler? And you don't need to use the Grazer bot. However the is some agar.io virus popper codes on internet.

**Comment by RealDebugMonkey** [comment]
It really would be harder to pull it out. The virus popper relies on lots of variables that have to be identified in the official code. It's not a trivial task by any means, which is why there aren't a lot of these projects (most are just copies/clones/rips of others). If I'm going to go through the effort of doing that I may as well just refresh the entire code base.

That said, I've been **very** busy ... but I'm trying to find the time to do a exactly that: a full refresh of the code with hopefully some advice on how to keep it updated. Then I'll probably hand the reigns over to PepinCZ here.

**Comment by ghost** [comment]
@RealDebugMonkey Full refresh of the code will definitely help. One thing that would be nice is standalone Grazer, but about virus popper... I don't know, it is little bit useless for me to make standalone everything.

**Comment by mrblah1** [comment]
So what we need is a kickstarter to see how much money we can raise for you to dedicate more time on this project.  I'll throw down $15.

**Comment by ghost** [comment]
@mrblah1 wow you would drop $15 to opensource project? You really a nice person. Im personaly not familiar with agar.io, but I think we dont need make everythink standalone. 1) All features in the code uses the "base", so its kinda hard to make it standalone. 2) This is "all-in-one" modification. Its pointless for me to make everythink standalone. One thing that can be good is to make standalone version of Grazer.

**Comment by RealDebugMonkey** [comment]
Sorry, stand-alone anything is going to have to be done by someone else. Probably by just tearing out the things they don't want.
